version: "3"

volumes:
  mongo-data: {}

services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    volumes:
      - "mongo-data:/data/db"
    ports:
      - 27017:27017
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
